core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('prestador/',include('prestador.urls'))
]

home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='index'),
    path('login/', views.pagina_login, name='login'),
    path('logar/', views.logar, name="logar"),
    path('registrar/', views.registrar, name='registrar'),
    path('criar/', views.criar, name='criar')
]

prestador/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('cadastro/', views.cadastrar_profissao, name='cadastro')
]

home/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Usuario(models.Model):
    nome_completo = models.CharField(max_length=50)
    cpf = models.CharField(max_length=11, unique=True)
    
class Role(models.Model):
    modalidade = models.CharField(max_length=1,
                                   choices=(('P', 'Prestador'),
                                            ('C', 'Contratante')))
    

prestador/models.py
from django.db import models

class Profissao(models.Model):
    profissao = models.CharField(max_length=255)
    tempo_experiencia = models.CharField(max_length=255)
    preco_por_hora = models.DecimalField(max_digits=10, decimal_places=2)
    foto = models.ImageField(upload_to='fotos/')  
    
    def __str__(self):
        return self.profissao

home/forms.py
from django import forms
from django.forms import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.http import HttpResponse
from django.contrib import messages

from home.models import Role

class UserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    password = forms.CharField(
        label="password",
        strip=False,
        widget=forms.PasswordInput(),
        help_text='Use the same password as before.',
        required=True,
        error_messages={
            'required': 'Password must not be empty'
        }
    )

    password2 = forms.CharField(
        label="password2",
        strip=False,
        widget=forms.PasswordInput(),
        help_text='Use the same password as before.',
        required=True,
        error_messages={
            'required': 'Please, repeat your password'
        }
    )

    class Meta:
        model = User
        fields = ['username', 'password']

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data['username']
        password = cleaned_data['password']
        password2 = cleaned_data['password2']
        if password != password2:
            password_confirmation_error = ValidationError(
                'Password and password2 must be equal',
                code='invalid'
            )
            raise ValidationError({
                'password': password_confirmation_error,
                'password2': [
                    password_confirmation_error,
                ],
            })
        
        if len(password) < 6:
            print(f"As senhas não podem ter menos de 6 caracteres e a sua tem {len(password)}")
            raise ValidationError("A senha deve ter pelo menos 6 caracteres", code='password_too_short')
        
        
        if username == password:
            print("O nome de usuário e a senha não podem ser iguais!!")
            raise ValidationError({"username":"O nome de usuário e a senha não podem ser iguais!!"})
            

        

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])  # Use set_password para garantir o hashing correto
        if commit:
            user.save()
        return user

class RoleForm(forms.ModelForm):

    modalidade = forms.CharField(
        label="modalidade",
        strip=False,
        help_text='Use the same password as before.',
        required=True,
        error_messages={
            'required': 'Please, repeat your password'
        }
    )

    class Meta:
        model = Role
        fields = '__all__'

home/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import Http404, HttpResponse, HttpResponseServerError
from django.http import request
from django.contrib.auth.hashers import make_password
from django.contrib import messages
from core.settings import constants
import time



from home.forms import UserForm, RoleForm
# Create your views here.



def home(request):
    return render(request, 'home/index.html')

def pagina_login(request):
    return render( request, 'home/login.html')

    
def logar(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('home:index')
    else:
        print("não ativa")
        raise 403
    

def registrar(request):
    register_form_data = request.session.get('register_form_data', None)
    form= UserForm(register_form_data)
    return render(request, "home/criar_conta.html", {"form": form})

def criar(request):
    if not request.POST:
        raise Http404()

    POST = request.POST
    request.session['register_form_data'] = POST
    form = UserForm(POST)

    username = request.POST.get("username")
    password = request.POST.get("password")

    if username == password:
        messages.error(request, "Usuário e senha não podem ser iguais!!") 

    if form.is_valid():
        form.save()
        del(request.session['register_form_data'])
        return redirect('home:login')
    else:
        messages.error(request, "Erro nos campos")    

    # Redirecione para a página de registro após processar o formulário,
    # independente de ser válido ou não.
    return redirect('home:registrar')

    

prestador/views.py
from django.shortcuts import render
from .models import Profissao
from django.contrib import messages
from core.settings import constants
# Create your views here.

def cadastrar_profissao(request):
    if request.method == 'POST':
        profissao = request.POST.get('profissao')
        tempo = request.POST.get('tempo')
        preco = request.POST.get('preco')
        foto = request.FILES.get('foto')

        if not profissao or not tempo or not preco or not foto:
            messages.error(request, 'Por favor, preencha todos os campos do formulário.')
        else:
            nova_profissao = Profissao(profissao=profissao,tempo_experiencia=tempo,preco_por_hora=preco,foto=foto)
            nova_profissao.save()

            messages.add_message(request, constants.SUCCESS, 'Profissão cadastrada com sucesso!')
            return render(request, 'cadastro.html', {'nova_profissao':nova_profissao})
    
    return render(request, 'cadastro.html')
    

home/templates/home/criar_conta.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Registrar conta</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'home/login/images/icons/favicon.ico'%}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/vendor/bootstrap/css/bootstrap.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/fonts/font-awesome-4.7.0/css/font-awesome.min.cs'%}s">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/vendor/animate/animate.css'%}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/vendor/css-hamburgers/hamburgers.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/vendor/animsition/css/animsition.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/vendor/select2/select2.min.css'%}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/vendor/daterangepicker/daterangepicker.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/css/util.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/css/main.css'%}">
<!--===============================================================================================-->

</head>
<body>
    <div class="limiter">
		<div class="container-login100" style="background-image: url('{% static 'home/login/images/bg-01.jpg'%}');">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					Criar conta
				</span>
				<form class="login100-form validate-form p-b-33 p-t-5" action = "{% url 'home:criar'%}" method = "post">
                    {% csrf_token %}
					{% if messages %}
						<div class="msg">
						<ul>
							{% for message in messages %}
							<li {% if message.tags %} class="{{ messages.tags }}"{% endif %}>{{ message }}</li>
							{% endfor %}
						</ul>
						</div>
					{% endif %}
					
					
                    <div class="wrap-input100 validate-input">
						<input class="input100" type="text" name="username" placeholder="Insira um nome de usuário">
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>

					
					<div class="wrap-input100 validate-input">
						<input class="input100" type="password" name="password" placeholder="Insira uma senha">
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					
                    <div class="wrap-input100 validate-input">
						<input class="input100" type="password" name="password2" placeholder="Repita a senha">
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					<div class="wrap-input100 validate-input">
						<label for="cars">Escolha a modalidade:</label>
								<select name="modalidade" id="modalidade" multiple>
								<option value="P">Prestador</option>
								<option value="C">Contratante</option>
								</select>
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>
                   
					<div class="container-login100-form-btn m-t-32">
						<button class="login100-form-btn" type="submit" value="registrar">
							Criar conta
						</button>	
					</div>
                </form>
			</div>
		</div>		
	</div>
</body>
</html>

home/templates/home/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'home/login/images/icons/favicon.ico'%}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/vendor/bootstrap/css/bootstrap.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/fonts/font-awesome-4.7.0/css/font-awesome.min.cs'%}s">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/vendor/animate/animate.css'%}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/vendor/css-hamburgers/hamburgers.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/vendor/animsition/css/animsition.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/vendor/select2/select2.min.css'%}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/vendor/daterangepicker/daterangepicker.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/css/util.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'home/login/css/main.css'%}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static 'home/login/images/bg-01.jpg'%}');">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					Account Login
				</span>
				<form class="login100-form validate-form p-b-33 p-t-5" method="post" action="{% url 'home:logar' %}">
				{% csrf_token %}
					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name="username" placeholder="User name">
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					<div class="container-login100-form-btn m-t-32">
						<button class="login100-form-btn" type="submit" value="Entrar">
							logar
						</button>	
										
				</form>
				<button class="login100-form-btn " type="button" value="Criar conta">
					<a href="{% url 'home:registrar' %}">Criar conta</a>
				</button>
			</div>
		</div>		
	</div>
	



	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'home/login/vendor/jquery/jquery-3.2.1.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'home/login/vendor/animsition/js/animsition.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'home/login/vendor/bootstrap/js/popper.js'%}"></script>
	<script src="{% static 'home/login/vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'home/login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'home/login/vendor/daterangepicker/moment.min.js'%}"></script>
	<script src="{% static 'home/login/vendor/daterangepicker/daterangepicker.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'home/login/vendor/countdowntime/countdowntime.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'home/login/js/main.js' %}"></script>

</body>
</html>

templates/cadastro.html
{% load static %}
    <html>
        <head>
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <title></title>
            <meta name="description" content="">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link href="{% static 'prestador/css/css.css' %}" rel="stylesheet">
        </head>
        <body>
            <br>
        <br>
        <div class="container">
            <h3 class="font-destaque">Ijob</h3>
            <h3 class="font-destaque">Aqui sua profissão IMPORTA </h3>

            <div class="row">
                <div class="col-md-3" style="text-align: center">
                    <img src="" alt="">
                    <h3>Preencha corretamente o formulario abaixo:</h3>
                </div>

                <div class="col-md-9">
                {% if messages %}
                    <br>
                    {% for message in messages %}
                        <div class="success-message {{ message.tags }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <label>Qual profissão?</label>
                        <br>
                        <input type="text" class="input-default" name="profissao">
                        <br>
                        <br>
                        <label>Tempo de experiencia:</label>
                        <br>
                        <input type="text" class="input-default" name="tempo">
                        <br>
                        <br>
                        <label>Preço por dia:</label>
                        <br>
                        <input type="text" class="input-default w100" name="preco">
                        <br>
                        <br>
                        <label for='foto'>Enviar fotos:</label>
                        <br>
                        <input type="file" class="input-default w100" name="foto">
                        <br>
                        <br>
                        <input type="submit" class="btn-default">
                    </form>
                </div> 
            </div>
        </div>   
        </body>
    </html>